name: CI – Parttrader Automation Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, test]

    env:
      TEST_ENV: ${{ matrix.env }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      # Optional: create .env dynamically from secrets
      #- name: Create .env file for ${{ matrix.env }}
      #  run: |
      #    echo "BASE_URL=${{ secrets['BASE_URL_' + matrix.env] }}" >> .env.${{ matrix.env }}
      #    echo "PASSWORD=${{ secrets['PASSWORD_' + matrix.env] }}" >> .env.${{ matrix.env }}

      - name: Compile TypeScript
        run: npm run compile

      - name: Lint code
        run: npm run lint

      - name: Install/ Update Playwright 
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
